### ISSUE TITLE
Use of gitconfig instead of shell aliases better

### ISSUE THREAD

**Issue by MarauderXtreme** [Feliix42/dotfiles#1]
Is there any particular reason besides "I started with that" why `git-yolo` or `safety-first` is a shell alias instead a configured git alias? Like:

```
[alias]
  yolo = push --force
```

This should be easier portable!

**Comment by Feliix42** [comment]
Yep, the only reason for this is that I wrote that at a time when I had no clue of how to do things properly and then never updated it :smile:
That repo is now going to go west in favor of a clean restart.
